import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '..\..\..\..\lib\prisma.ts'
import { verifyToken } from '..\..\..\..\lib\auth.ts'

// PATCH - Check bàn giao trước/sau khi sử dụng (chỉ Admin)
export async function PATCH(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const token = request.cookies.get('auth-token')?.value
    if (!token) {
      return NextResponse.json(
        { message: 'Không có quyền truy cập' },
        { status: 401 }
      )
    }

    const user = verifyToken(token)
    if (!user || user.role !== 'ADMIN') {
      return NextResponse.json(
        { message: 'Chỉ admin mới có quyền check bàn giao' },
        { status: 403 }
      )
    }

    const { type, notes } = await request.json() // type: 'BEFORE' hoặc 'AFTER'

    if (!['BEFORE', 'AFTER'].includes(type)) {
      return NextResponse.json(
        { message: 'Loại check bàn giao không hợp lệ' },
        { status: 400 }
      )
    }

    const booking = await prisma.culturalCenterBooking.findUnique({
      where: { id: params.id },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true
          }
        },
        culturalCenter: {
          select: {
            id: true,
            name: true,
            building: true
          }
        }
      }
    })

    if (!booking) {
      return NextResponse.json(
        { message: 'Không tìm thấy lịch đặt' },
        { status: 404 }
      )
    }

    const now = new Date()
    const updateData: any = {
      handoverNotes: notes || null
    }

    if (type === 'BEFORE') {
      // Check bàn giao trước khi dùng
      if (booking.handoverBeforeChecked) {
        return NextResponse.json(
          { message: 'Đã check bàn giao trước khi dùng rồi' },
          { status: 400 }
        )
      }

      updateData.handoverBeforeChecked = true
      updateData.handoverBeforeCheckedBy = user.id
      updateData.handoverBeforeCheckedAt = now

      // Thông báo cho người đặt
      await prisma.notification.create({
        data: {
          title: 'Đã check bàn giao trước khi sử dụng',
          message: `Lịch đặt "${booking.title}" tại ${booking.culturalCenter.name} đã được check bàn giao. Bạn có thể sử dụng.`,
          userId: booking.userId,
          type: 'SUCCESS',
          autoGenerated: true
        }
      })
    } else {
      // Check bàn giao sau khi dùng
      if (!booking.handoverBeforeChecked) {
        return NextResponse.json(
          { message: 'Cần check bàn giao trước khi dùng trước' },
          { status: 400 }
        )
      }

      if (booking.handoverAfterChecked) {
        return NextResponse.json(
          { message: 'Đã check bàn giao sau khi dùng rồi' },
          { status: 400 }
        )
      }

      updateData.handoverAfterChecked = true
      updateData.handoverAfterCheckedBy = user.id
      updateData.handoverAfterCheckedAt = now

      // Thông báo cho người đặt
      await prisma.notification.create({
        data: {
          title: 'Đã hoàn tất check bàn giao',
          message: `Lịch đặt "${booking.title}" tại ${booking.culturalCenter.name} đã hoàn tất check bàn giao sau khi sử dụng.`,
          userId: booking.userId,
          type: 'SUCCESS',
          autoGenerated: true
        }
      })
    }

    const updatedBooking = await prisma.culturalCenterBooking.update({
      where: { id: params.id },
      data: updateData,
      include: {
        culturalCenter: {
          select: {
            id: true,
            name: true,
            building: true
          }
        },
        user: {
          select: {
            id: true,
            name: true
          }
        }
      }
    })

    return NextResponse.json(updatedBooking)
  } catch (error) {
    console.error('Error updating handover:', error)
    return NextResponse.json(
      { message: 'Có lỗi xảy ra khi cập nhật bàn giao' },
      { status: 500 }
    )
  }
}

